name: Release Packaging

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    name: Release Packaging
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [
          aarch64-linux-android, armv7-linux-androideabi, i686-linux-android,
          x86_64-linux-android, i686-unknown-linux-gnu, x86_64-unknown-linux-gnu,
          x86_64-apple-darwin, aarch64-apple-ios, i686-pc-windows-gnu,
          x86_64-pc-windows-gnu, i686-pc-windows-msvc, x86_64-pc-windows-msvc,
          wasm32-unknown-emscripten,
        ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: davidB/rust-cargo-make@v1
      - name: Release Build
        run: cargo make export-${{ matrix.target }}-release
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: slippery-${{ matrix.target }}
          path: bin/${{ matrix.target }}/
